spring:
  web:
    resources:
      static-locations: "file:/static-files"
  mvc:
    static-path-pattern: "/static/**"
  jackson:
    serialization:
      INDENT_OUTPUT: true

management:
  endpoints:
    web:
      base-path: /

app:
  deployment-type: local
  environment-endpoint:
    enabled: false
    filtered-prefixes: APPSETTING_, WEBSITE_, IDENTITY_, MSI_
