spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

management:
  endpoints:
    web:
      base-path: /

app:
  environment-endpoint:
    enabled: false
    filtered-prefixes: APPSETTING_, WEBSITE_, IDENTITY_, MSI_
